// For User

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_NEW_TOKEN = 'GET_NEW_TOKEN';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

// For Home Screen

export const GET_HOME_COURSES = 'GET_HOME_COURSES';
export const GET_ALL_SUBSCRIBED_COURSES = 'GET_ALL_SUBSCRIBED_COURSES';

// For wishlist

export const GET_WISHLIST = 'GET_WISHLIST';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';

// For Search

export const GET_ALL_COURSE_CATEGORY = 'GET_ALL_COURSE_CATEGORY';
export const GET_ALL_SEARCHED_COURSES = 'GET_ALL_SEARCHED_COURSES';

// For Main Screen

export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_VIDEOS = 'GET_VIDEOS';
export const ADD_RECENT_VIDEO = 'ADD_RECENT_VIDEO';
export const GET_DESCRIPTIONS = 'GET_DESCRIPTIONS';
export const ADD_NOTE = 'ADD_NOTE';
export const READ_NOTES = 'READ_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const READ_REVIEWS = 'READ_REVIEWS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const READ_FAQ = 'READ_FAQ';
export const READ_ASSESSMENT = 'READ_ASSESSMENT';
export const SUBMIT_ASSESSMENT = 'SUBMIT_ASSESSMENT';
export const UPDATE_ASSESSMENT = 'UPDATE_ASSESSMENT';
export const SET_COURSE_ID = 'SET_COURSE_ID';
